# -*- coding: utf-8 -*-
"""Team1_DMBIUI24

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ZOTFJsSJ44soz8cFjBD2unHAy8MmKHq

**Kelompok 1 Tugas Regresi Data Mining B 2024/2025**

# <left><h2><strong><font color="lightseagreen">Kelompok 1</font></strong></h2></left>
|Nama|NPM|Tingkat Kontribusi
|---|---|---|
|Kayla Zahira Amadya|2206053890|100%|
|Gian Sinar Katulistiwa|2206031675|100%|
|Farah Khairunnisa Prakasa|2206053890|100%|
|Yiesha Reyhani Ghozali|2206828115|100%|
|Muhammad Riesya Attaya |2206051494|100%|

# **Pendahuluan**

##**Data**
Dataset yang digunakan diambil dari Kompetisi House Prices - Advanced Regression Techniques pada Kaggle dengan 1460 observasi dan 81 variabel yang memuat informasi terkait rumah/properti di Ames, Iowa. Variabel-variabel tersebut mencakup karakteristik fisik, fasilitas, kondisi interior, kondisi lingkungan, hingga informasi penjualan. Dataset dapat diakses melalui [link berikut](https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques/overview).

##**Tujuan**

Dengan memahami faktor-faktor yang memengaruhi harga jual rumah, akan dibentuk model regresi untuk memprediksi nilai properti berdasarkan karakteristiknya. Hal ini dapat membantu pembeli, penjual, dan agen real estate untuk menentukan harga jual atau beli yang sesuai. Selain itu, prediksi harga jual properti juga dapat membantu pemilik rumah untuk mengetahui elemen rumah yang paling berpengaruh terhadap nilai jual, sehingga memungkinkan renovasi atau penyesuaian properti yang lebih efektif.

##**Variabel**

*   SalePrice: Harga jual properti dalam dolar. (Variabel Target)
*   MSSubClass: Kelas bangunan
* MSZoning: Klasifikasi zona umum
* LotFrontage: Panjang jalan (dalam kaki linear) yang terhubung ke properti
* LotArea: Luas tanah dalam kaki persegi
* Street: Jenis akses jalan
* Alley: Jenis akses gang
* LotShape: Bentuk umum properti
* LandContour: Kerataan properti
* Utilities: Jenis utilitas yang tersedia
* LotConfig: Konfigurasi tanah
* LandSlope: Kemiringan properti
* Neighborhood: Lokasi fisik di dalam batas kota Ames
* Condition1: Kedekatan dengan jalan utama atau rel kereta api
* Condition2: Kedekatan dengan jalan utama atau rel kereta api (jika ada yang kedua)
* BldgType: Jenis tempat tinggal
* HouseStyle: Gaya tempat tinggal
* OverallQual: Kualitas keseluruhan bahan dan penyelesaian
* OverallCond: Penilaian kondisi keseluruhan
* YearBuilt: Tahun konstruksi awal
* YearRemodAdd: Tahun renovasi
* RoofStyle: Jenis atap
* RoofMatl: Material atap
* Exterior1st: Penutup eksterior rumah
* Exterior2nd: Penutup eksterior rumah (jika menggunakan lebih dari satu material)
* MasVnrType: Jenis veneer batu
* MasVnrArea: Luas veneer batu dalam kaki persegi
* ExterQual: Kualitas material eksterior
* ExterCond: Kondisi material eksterior saat ini
* Foundation: Jenis pondasi
* BsmtQual: Tinggi basement
* BsmtCond: Kondisi umum basement
* BsmtExposure: Dinding basement walkout atau tingkat taman
* BsmtFinType1: Kualitas area basement yang selesai
* BsmtFinSF1: Luas basement selesai tipe 1 dalam kaki persegi
* BsmtFinType2: Kualitas area selesai kedua (jika ada)
* BsmtFinSF2: Luas basement selesai tipe 2 dalam kaki persegi
* BsmtUnfSF: Luas basement yang tidak selesai dalam kaki persegi
* TotalBsmtSF: Total luas basement dalam kaki persegi
* Heating: Jenis pemanas
* HeatingQC: Kualitas dan kondisi pemanas
* CentralAir: Pendingin udara sentral
* Electrical: Sistem listrik
* 1stFlrSF: Luas lantai pertama dalam kaki persegi
* 2ndFlrSF: Luas lantai kedua dalam kaki persegi
* LowQualFinSF: Luas lantai selesai berkualitas rendah (semua lantai)
* GrLivArea: Luas area tinggal di atas permukaan tanah dalam kaki persegi
* BsmtFullBath: Jumlah kamar mandi penuh di basement
* BsmtHalfBath: Jumlah kamar mandi setengah di basement
* FullBath: Jumlah kamar mandi penuh di atas permukaan tanah
* HalfBath: Jumlah kamar mandi setengah di atas permukaan tanah
* Bedroom: Jumlah kamar tidur di atas tingkat basement
* Kitchen: Jumlah dapur
* KitchenQual: Kualitas dapur
* TotRmsAbvGrd: Total jumlah ruangan di atas permukaan tanah (tidak termasuk kamar mandi)
* Functional: Penilaian fungsionalitas rumah
* Fireplaces: Jumlah perapian
* FireplaceQu: Kualitas perapian
* GarageType: Lokasi garasi
* GarageYrBlt: Tahun pembangunan garasi
* GarageFinish: Finishing interior garasi
* GarageCars: Kapasitas garasi berdasarkan jumlah mobil
* GarageArea: Luas garasi dalam kaki persegi
* GarageQual: Kualitas garasi
* GarageCond: Kondisi garasi
* PavedDrive: Jalan beraspal
* WoodDeckSF: Luas dek kayu dalam kaki persegi
* OpenPorchSF: Luas teras terbuka dalam kaki persegi
* EnclosedPorch: Luas teras tertutup dalam kaki persegi
* 3SsnPorch: Luas teras tiga musim dalam kaki persegi
* ScreenPorch: Luas teras dengan layar dalam kaki persegi
* PoolArea: Luas kolam renang dalam kaki persegi
* PoolQC: Kualitas kolam renang
* Fence: Kualitas pagar
* MiscFeature: Fitur tambahan yang tidak tercakup dalam kategori lain
* MiscVal: Nilai ($) fitur tambahan
* MoSold: Bulan penjualan
* YrSold: Tahun penjualan
* SaleType: Jenis penjualan
* SaleCondition: Kondisi penjualan

## Keterangan variabel
"""

!cat /content/regresi/data_description.txt # run setelah import data

"""# Import Packages & Load Data"""

# Library Pemrosesan Data
import numpy as np
import pandas as pd

# Library untuk Visualisasi Data
import matplotlib.pyplot as plt
import seaborn as sns
!pip install hvplot
import hvplot.pandas

# Library untuk metrik dan Pre Processing
from sklearn import metrics
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score

# Library untuk Modelling
from sklearn.linear_model import LinearRegression, SGDRegressor, Lasso, Ridge, ElasticNet
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, BaggingRegressor, ExtraTreesRegressor, AdaBoostRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor

# Library untuk handle warning
import warnings
warnings.filterwarnings('ignore')
sns.set()

# Supaya dapat melihat seluruh kolom
pd.set_option('display.max_columns', None)

# Set seed untuk random state
SEED = 42

# Import Data
!gdown --folder 1MTtb2V-CT7Fx6q6khN5X9zLRZBx25eht

# Load Data
df_train = pd.read_csv('/content/regresi/train.csv')
df_test = pd.read_csv('/content/regresi/test.csv')

df_train.head()

# Melihat informasi pada data
df_train.info()

"""Data memiliki 81 variabel serta 1460 observasi dengan satu variabel respon, yaitu "SalePrice" dan 80 variabel penjelas.

Terdapat beberapa tipe variabel yang kurang tepat, seperti `MSSubClass` yang seharusnya adalah variabel kategorik (sesuai deskripsi data), `BsmtFullBath`, `BsmtHalfBath`, dan `GarageCars` yang seharusnya adalah integer.
"""

# Mengubah tipe kolom
df_train['MSSubClass'] = df_train['MSSubClass'].astype('object', copy=False)
df_train['BsmtFullBath'] = df_train['BsmtFullBath'].astype('int64', copy=False)
df_train['BsmtHalfBath'] = df_train['BsmtHalfBath'].astype('int64', copy=False)
df_train['GarageCars'] = df_train['GarageCars'].astype('int64', copy=False)

# Melihat kolom yang dimiliki oleh data
df_train.columns

"""# EDA"""

# Drop kolom 'Id'
df_train = df_train.drop('Id', axis=1)

# Data dengan variabel numerik saja
num_cols = df_train.select_dtypes(include=['number']).columns

# Data dengan variabel kategorik saja
categorical_cols = df_train.select_dtypes(include=['object', 'category']).columns

"""## Variabel Numerik"""

# Melihat statistik deskriptif dari masing-masing variabel numerik
df_train.describe()

"""Terlihat nilai-nilai statistik deskriptif yang dimiliki oleh variabel numerik."""

# Membuat histogram dan boxplot untuk setiap kolom numerik
for col in num_cols:
    # Membuat figure dan axes
    fig, axes = plt.subplots(1, 2, figsize=(15, 5))

    # Histogram untuk sebaran data
    sns.histplot(df_train[col], kde=True, ax=axes[0])
    axes[0].set_title(f"Histogram of {col}")

    # Boxplot untuk melihat outlier
    sns.boxplot(x=df_train[col], ax=axes[1])
    axes[1].set_title(f"Boxplot of {col}")

    # Menampilkan plot
    plt.tight_layout()
    plt.show()

"""Terlihat bahwa sebaran data pada beberapa variabel mengikuti distribusi normal, seperti `TotalBsmtSF`, `1stFlrSF`, dan `SalePrice`. Kemudian, terlihat juga terdapat beberapa outliers pada beberapa variabel numerik seperti `LotFrontage`, `LotArea`, dan `MasVnrArea`."""

# Distribusi Variabel SalePrice
sns.distplot(df_train['SalePrice'])

"""Terlihat Variabel SalePrice memiliki
*   Deviasi dari distribusi normal
*   Skewness positif yang signifikan
* Ketajaman puncak

"""

#Melihat Skewness dan Kurtosis pada SalePrice
print("Skewness: %f" % df_train['SalePrice'].skew())
print("Kurtosis: %f" % df_train['SalePrice'].kurt())

"""Terlihat bahwa data memiliki
*   **Skewness**: 1.883, yang berartu sebagian besar data terdistribusi di sisi kiri, sementara sisi kanan memiliki ekor panjang.
*   **Kurtosis**: 6.536, yang berarti data memiliki puncak yang lebih tajam dan ekor yang lebih berat dibanding distribusi normal, yang berarti lebih banyak nilai ekstrem atau outlier.


"""

# Plot untuk setiap variabel numerik terhadap variabel respon (SalePrice)
for col in num_cols:
    if col != 'SalePrice':  # Menghindari plotting SalePrice terhadap dirinya sendiri
        plt.figure(figsize=(8, 6))
        sns.scatterplot(x=df_train[col], y=df_train['SalePrice'])
        plt.title(f'Relationship between {col} and SalePrice')
        plt.xlabel(col)
        plt.ylabel('SalePrice')
        plt.show()

"""## Variabel Kategorik"""

# Plot boxplot untuk variabel kategorikal terhadap SalePrice
for col in categorical_cols:
    plt.figure(figsize=(8, 6))
    sns.boxplot(x=df_train[col], y=df_train['SalePrice'])
    plt.title(f'Boxplot of {col} vs SalePrice')
    plt.xlabel(col)
    plt.ylabel('SalePrice')
    plt.xticks(rotation=90)  # Rotasi label sumbu x jika kategori terlalu panjang
    plt.show()

# Bar Chart

# Subplot
n_cols = 3
n_rows = (len(categorical_cols) + n_cols - 1) // n_cols  # Hitung jumlah baris
fig, axes = plt.subplots(n_rows, n_cols, figsize=(15, n_rows * 4))

# Flat axes untuk iterasi
axes = axes.flatten()

# Countplot untuk setiap kolom kategori
for i, col in enumerate(categorical_cols):
    sns.countplot(x=col, alpha=0.7, data=df_train, ax=axes[i], palette="Set1")
    axes[i].set_title(col, fontsize=12)
    axes[i].set_xticklabels(axes[i].get_xticklabels(), rotation=45, ha='right')  # Setelah plot dibuat

fig.tight_layout()
plt.show()

"""Plot di atas menggambarkan jumlah dari masing-masing nilai pada masing-masing variabel kategorik. Terlihat bahwa cukup banyak variabel yang memiliki sebaran data yang tidak seimbang.

Sebagai contoh, variabel `MasVnrType` memiliki nilai 'BrkFace' sekitar 450 observasi, 'Stone' sekitar 120 observasi, dan 'BrkCmn' sekitar 10 observasi.
"""

# Jumlah masing-masing nilai unik pada Utilities
df_train['Utilities'].value_counts()

"""Perhatikan bahwa dataset hanya memiliki 1 observasi untuk rumah dengan tipe peralatan `NoSeWa` (Hanya listrik dan gas) pada fitur `Utilities`. Hal ini berarti kontribusi fitur `Utilities` terhadap model kemungkinan kecil dan dapat menyebabkan noise. Oleh karena itu, variabel ini akan dihapus dan tidak diikutsertakan dalam model."""

# Drop Utilities
df_train = df_train.drop('Utilities', axis=1)

"""## Matriks Korelasi"""

# Matriks korelasi untuk semua variabel numerik
corrmat = df_train[num_cols].dropna().corr()
f, ax = plt.subplots(figsize=(12, 9))
sns.heatmap(corrmat, cmap="coolwarm", vmin=0, vmax=1, center=0, square=True, annot=False)

# Melihat korelasi antara 10 variabel numerik yang sangat berkorelasi dengan variabel SalePrice
k = 10 #number of variables for heatmap
cols = corrmat.nlargest(k, 'SalePrice')['SalePrice'].index
cm = np.corrcoef(df_train[cols].values.T)
sns.set(font_scale=1.25)
hm = sns.heatmap(cm, cbar=True, annot=True, square=True, fmt='.2f', annot_kws={'size': 10}, yticklabels=cols.values, xticklabels=cols.values)
plt.show()

"""Terlihat bahwa variabel yang berkorelasi sangat kuat dengan `SalePrice` adalah `OverallQual`, `GrLivArea`, `GarageCars`, `GarageArea`, `TotalBsmtSF`, `1stFlrSF`, `FullBath`, `TotRmsAbvGrd`, dan `YearBuilt`.

# Pre Processing

## Train

### Missing Values
"""

# Jumlah Missing Values
total = df_train.isnull().sum().sort_values(ascending=False)
percent = (df_train.isnull().sum()/df_train.isnull().count()).sort_values(ascending=False)
missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_data.head(20)

"""Terlihat bahwa terdapat 19 kolom yang memiliki missing values.

Semua variabel dengan missing values lebih dari 100, akan dihapus

"""

# Menghapus kolom yang memiliki lebih dari 100 missing values dan jadikan dataframe baru
df_train2 = df_train.dropna(thresh=len(df_train)-100, axis=1)

"""
Variabel `Electrical` hanya memiliki 1 missing value. Kita akan mengimputasinya dengan modus berdasarkan neighborhood.

Variabel `MasVnrArea` hanya memiliki 8 missing value. Kita akan mengimputasinya dengan median berdasarkan neighborhood."""

# Menghitung modus per Neighborhood untuk 'Electrical'
mode = df_train2.groupby('Neighborhood')['Electrical'].agg(lambda x: x.mode()[0])

# Menghitung median per Neighborhood untuk MasVnrArea
median_values = df_train2.groupby('Neighborhood')['MasVnrArea'].median()

# Mengisi missing values pada kolom 'Electrical' berdasarkan modus dari grup 'Neighborhood'
df_train2['Electrical'].fillna(df_train2['Neighborhood'].map(mode), inplace=True)

# Mengisi missing values pada kolom 'MasVnrArea' berdasarkan median dari grup 'Neighborhood'
df_train2['MasVnrArea'].fillna(df_train2['Neighborhood'].map(median_values), inplace=True)

"""Berdasarkan deskripsi data, fitur-fitur Basement dan Garage yang berisi `Na` diinterpretasikan sebagai "Tidak memiliki". Sehingga, akan diimputasi dengan 0."""

# Daftar variabel
garage = ['GarageCond', 'GarageQual', 'GarageType', 'GarageFinish', 'GarageYrBlt']
bsmt = ['BsmtFinType2', 'BsmtFinType1', 'BsmtExposure', 'BsmtCond', 'BsmtQual']

# Menentukan kolom kategorikal dan numerik
cats = df_train2.columns[df_train2.dtypes == 'object']
nums = list(set(df_train2.columns) - set(cats))

# Mengisi missing values dengan '0'
df_train2[cats] = df_train2[cats].fillna('0')
df_train2[nums] = df_train2[nums].fillna(0)

# Menampilkan jumlah missing values setelah penanganan
missing_data = df_train2.isnull().sum().sort_values(ascending=False)
print(missing_data.head(20))

"""Terlihat bahwa sudah tidak terdapat missing values."""

# Melihat informasi pada data
df_train2['MSSubClass'] = df_train2['MSSubClass'].astype('object', copy=False)
df_train2.info()

"""Sekarang data mengandung 71 variabel.

### Outliers dan Duplicate
"""

# Melihat apakah terdapat outlier pada data numerik
Q1 = df_train2[nums].quantile(0.25)
Q3 = df_train2[nums].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = (df_train2[nums] < lower_bound) | (df_train2[nums] > upper_bound)

outlier_data = df_train2[nums][outliers.any(axis=1)]  # Menyaring data dengan outliers
print(f"Jumlah data yang mengandung outlier: {outlier_data.shape[0]}")

"""Terlihat bahwa terdapat 861 outliers pada data.

Namun, dengan mempertimbangkan harga rumah yang sangat bervariasi, di mana outliers mencerminkan properti eksklusif atau kondisi pasar tertentu, sehingga outliers tidak akan dihapus
"""

# Mengecek apakah ada baris duplikat
duplicate_rows = df_train2[df_train2.duplicated()]
print(duplicate_rows)

"""Tidak terdapat baris yang duplikat

### Encoding Variabel Kategorik

Untuk variabel kategorik yang mungkin memiliki informasi terkait urutannya, akan digunakan `Label Encoder`.
"""

# Set Kolom
cols = ('BsmtQual', 'BsmtCond', 'GarageQual', 'GarageCond',
        'ExterQual', 'ExterCond','HeatingQC', 'KitchenQual', 'BsmtFinType1',
        'BsmtFinType2', 'Functional', 'BsmtExposure', 'GarageFinish', 'LandSlope',
        'LotShape', 'PavedDrive', 'Street', 'CentralAir', 'MSSubClass', 'OverallCond',
        'YrSold', 'MoSold')

# Apply LabelEncoder
for c in cols:
    lbl = LabelEncoder()
    lbl.fit(df_train2[c])
    df_train2[c] = lbl.transform(df_train2[c])

df_train2.head()

# One-Hot Encoding
train = pd.get_dummies(df_train2)
train.head()

"""Variabel yang menyatakan "Tidak memiliki fitur" kurang tepat untuk memperlakukan '0' sebagai kategori normal. Sehingga, akan di drop fitur hasil dummies yang memiliki '_0' pada nama fiturnya."""

# Drop
var_list = bsmt + garage
for feat in train.columns:
    if ('_0' in feat) and (feat.split("_")[0] in var_list):
        train.drop(feat, axis=1, inplace=True)

df_train2.shape

"""Sekarang, terdapat 1460 observasi dan 72 variabel pada data train2."""

train.shape

"""Terdapat 1460 observasi dan 206 kolom pada train.

## Test
"""

df_test.head()

df_test.info()

"""Terdapat 80 variabel dan 1459 observasi pada data test."""

# Drop kolom 'Id' dan 'Utilities'
df_test = df_test.drop('Id', axis=1)
df_test = df_test.drop('Utilities', axis=1)

"""### Missing Values"""

# Menghitung berapa banyak dan berapa persentase missing values dari masing-masing kolom
total = df_test.isnull().sum().sort_values(ascending=False)
percent = (df_test.isnull().sum()/df_test.isnull().count()).sort_values(ascending=False)
missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_data.head(35)

# Menghapus kolom yang memiliki missing values lebih besar dari 100
cols_to_drop = ['PoolQC', 'MiscFeature', 'Alley', 'Fence', 'MasVnrType', 'FireplaceQu', 'LotFrontage']
cols_to_drop = [col for col in cols_to_drop if col in df_test.columns]

# Drop the specified columns
df_test = df_test.drop(cols_to_drop, axis=1)

# Kolom yang diisi berdasarkan median
median_cols = ['MasVnrArea']

# Mengisi missing values berdasarkan median untuk setiap kolom di median_cols
for col in median_cols:
    median_values = df_test.groupby('Neighborhood')[col].median()
    df_test[col].fillna(df_test['Neighborhood'].map(median_values), inplace=True)

# Kolom yang diisi berdasarkan modus
mode_cols = ['MSZoning', 'Exterior1st', 'Exterior2nd', 'SaleType']

# Mengisi missing values berdasarkan modus untuk setiap kolom di mode_cols
for col in mode_cols:
    mode_values = df_test.groupby('Neighborhood')[col].agg(lambda x: x.mode()[0])
    df_test[col].fillna(df_test['Neighborhood'].map(mode_values), inplace=True)

# Mengisi missing values di kolom Functional dengan 'Typ'
df_test['Functional'].fillna('Typ', inplace=True)

# Mengisi missing values di kolom KitchenQual dengan 'TA'
df_test['KitchenQual'].fillna('TA', inplace=True)

# Daftar variabel
garage = ['GarageCond', 'GarageQual', 'GarageType', 'GarageFinish', 'GarageYrBlt',
          'GarageArea', 'GarageCars']
bsmt = ['BsmtFinType2', 'BsmtFinType1', 'BsmtExposure', 'BsmtCond', 'BsmtQual',
        'BsmtFinSF1', 'BsmtFinSF2', 'BsmtFullBath', 'BsmtHalfBath', 'BsmtUnfSF',
        'TotalBsmtSF']

# Menentukan kolom kategorikal dan numerik
cats = df_test.columns[df_test.dtypes == 'object']
nums = list(set(df_test.columns) - set(cats))

# Mengisi missing values dengan '0'
df_test[cats] = df_test[cats].fillna('0')
df_test[nums] = df_test[nums].fillna(0)

# Menampilkan jumlah missing values setelah penanganan
missing_data = df_test.isnull().sum().sort_values(ascending=False)
print(missing_data.head(10))

df_test.info()

# Mengubah tipe kolom
df_test['MSSubClass'] = df_test['MSSubClass'].astype('object', copy=False)
df_test['BsmtFullBath'] = df_test['BsmtFullBath'].astype('int64', copy=False)
df_test['BsmtHalfBath'] = df_test['BsmtHalfBath'].astype('int64', copy=False)
df_test['GarageCars'] = df_test['GarageCars'].astype('int64', copy=False)

"""### Encoding Variabel Kategorik"""

# Set Kolom
cols = ('BsmtQual', 'BsmtCond', 'GarageQual', 'GarageCond',
        'ExterQual', 'ExterCond','HeatingQC', 'KitchenQual', 'BsmtFinType1',
        'BsmtFinType2', 'Functional', 'BsmtExposure', 'GarageFinish', 'LandSlope',
        'LotShape', 'PavedDrive', 'Street', 'CentralAir', 'MSSubClass', 'OverallCond',
        'YrSold', 'MoSold')

# Apply LabelEncoder
for c in cols:
    lbl = LabelEncoder()
    lbl.fit(df_test[c])
    df_test[c] = lbl.transform(df_test[c])

# One-Hot Encoding
df_test = pd.get_dummies(df_test)
df_test.head()

# Drop
var_list = bsmt + garage
for feat in df_test.columns:
    if ('_0' in feat) and (feat.split("_")[0] in var_list):
        df_test.drop(feat, axis=1, inplace=True)

# Kolom yang ada di Train tapi tidak ada di df_test
set(train.columns) - set(df_test.columns)

"""Terdapat 15 variabel yang terdapat pada data train3, namun tidak terdapat pada data test."""

# Menyesuaikan kolom test dengan train
for col in train.columns:
    if col != 'SalePrice' and col not in df_test.columns:
        df_test[col] = 0

df_test.shape

"""# Data Scalling"""

# Data Train
scal_col = nums + list(cols)

scaler = StandardScaler()
train_scale = train.copy()
train_scale[scal_col] = scaler.fit_transform(train[scal_col])
train_scale.head()

# Memverifikasi apakah scalling dilakukan dengan benar
print(train_scale[scal_col].mean())  # Harus dekat dengan 0
print(train_scale[scal_col].std())   # Harus dekat dengan 1

"""Karena mean dari masing-masing variabel semua mendekati 0 dan standar deviasi dari masing-masing variabel semua mendekati 1, maka data scalling yang dilakukan sudah benar."""

# Data Test
cats = df_test.columns[df_test.dtypes == 'object']
nums2 = list(set(df_test.columns) - set(cats))

scal_col2 = nums2 + list(cols)
scaler2 = StandardScaler()
test_scale = df_test.copy()
test_scale[scal_col2] = scaler.fit_transform(df_test[scal_col2])
test_scale.head()

"""# Modelling"""

# Data splitting with scaling
X = train_scale.drop('SalePrice', axis=1)
y = train_scale['SalePrice']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=SEED)

def cross_val(model):
    pred = cross_val_score(model, X, y, cv=10)
    return pred.mean()

def print_evaluate(true, predicted):
    mae = metrics.mean_absolute_error(true, predicted)
    mse = metrics.mean_squared_error(true, predicted)
    rmse = np.sqrt(metrics.mean_squared_error(true, predicted))
    r2_square = metrics.r2_score(true, predicted)
    print('MAE:', mae)
    print('MSE:', mse)
    print('RMSE:', rmse)
    print('R2 Square', r2_square)
    print('__________________________________')

def evaluate(true, predicted):
    mae = metrics.mean_absolute_error(true, predicted)
    mse = metrics.mean_squared_error(true, predicted)
    rmse = np.sqrt(metrics.mean_squared_error(true, predicted))
    r2_square = metrics.r2_score(true, predicted)
    return mae, mse, rmse, r2_square

"""## Linear Regression"""

lin_reg = LinearRegression()
lin_reg.fit(X_train,y_train)

# print the intercept
print(lin_reg.intercept_)

coeff_df = pd.DataFrame(lin_reg.coef_, X.columns, columns=['Coefficient'])
coeff_df

pred = lin_reg.predict(X_test)

pd.DataFrame({'True Values': y_test, 'Predicted Values': pred}).hvplot.scatter(x='True Values', y='Predicted Values')

pd.DataFrame({'Error Values': (y_test - pred)}).hvplot.kde()

test_pred = lin_reg.predict(X_test)
train_pred = lin_reg.predict(X_train)

print('Test set evaluation:\n_____________________________________')
print_evaluate(y_test, test_pred)
print('Train set evaluation:\n_____________________________________')
print_evaluate(y_train, train_pred)

results_df = pd.DataFrame(data=[["Linear Regression", *evaluate(y_test, test_pred) , cross_val(LinearRegression())]],
                          columns=['Model', 'MAE', 'MSE', 'RMSE', 'R2 Square', "Cross Validation"])

"""Hasil evaluasi model Linear Regression menunjukkan overfitting yang sangat parah. Pada data training, model memiliki performa yang baik dengan nilai R² sebesar 0.92 (ini mungkin terpengaruh juga oleh banyaknya jumlah variabel). Nilai MAE, MSE, dan RMSEnya juga menunjukkan keakuratan yang cukup baik. Namun, pada data test, nilai R² menjadi negatif yang sangat besar (-1.6 x 10¹⁶), menunjukkan bahwa model benar-benar gagal dalam memprediksi data test. Nilai MAE, MSE, dan RMSEnya juga melonjak naik. Jadi, Linear Regression Model kurang baik untuk memprediksi harga rumah.

## Ridge Regression
"""

model = Ridge(alpha=100, solver='cholesky', tol=0.0001, random_state=42)
model.fit(X_train, y_train)
pred = model.predict(X_test)

test_pred = model.predict(X_test)
train_pred = model.predict(X_train)

print('Test set evaluation:\n_____________________________________')
print_evaluate(y_test, test_pred)
print('====================================')
print('Train set evaluation:\n_____________________________________')
print_evaluate(y_train, train_pred)

results_df_2 = pd.DataFrame(data=[["Ridge Regression", *evaluate(y_test, test_pred) , cross_val(Ridge())]],
                            columns=['Model', 'MAE', 'MSE', 'RMSE', 'R2 Square', "Cross Validation"])
results_df = pd.concat([results_df, results_df_2], ignore_index=True)

"""Hasil evaluasi model Ridge Regression menunjukkan performa model yang lebih baik dari Linear Regression. Nilai R² yang serupa pada data train dan test menunjukkan bahwa model ini dapat menggeneralisasi dengan baik. Selain itu, nilai MAE, MSE, dan RMSE pada data train dan test relatif kecil dan tidak menunjukkan perbedaan yang signifikan. Hal ini mengindikasikan bahwa model mampu memprediksi dengan baik pada kedua dataset, tanpa menunjukkan indikasi overfitting maupun underfitting.

## LASSO Regression
"""

from sklearn.linear_model import Lasso

model = Lasso(alpha=0.1,
              precompute=True,
#               warm_start=True,
              positive=True,
              selection='random',
              random_state=42)
model.fit(X_train, y_train)

test_pred = model.predict(X_test)
train_pred = model.predict(X_train)

print('Test set evaluation:\n_____________________________________')
print_evaluate(y_test, test_pred)
print('====================================')
print('Train set evaluation:\n_____________________________________')
print_evaluate(y_train, train_pred)

results_df_2 = pd.DataFrame(data=[["Lasso Regression", *evaluate(y_test, test_pred) , cross_val(Lasso())]],
                            columns=['Model', 'MAE', 'MSE', 'RMSE', 'R2 Square', "Cross Validation"])
results_df = pd.concat([results_df, results_df_2], ignore_index=True)

"""Model Lasso Regression menunjukkan hasil yang baik dengan kemampuan untuk menjelaskan sekitar 75-76% variasi data, berdasarkan nilai R² yang cukup tinggi pada kedua set data (train dan test). Meskipun ada sedikit perbedaan antara data train dan data test, di mana model sedikit lebih akurat pada data train (dengan MAE 0.2968 dan RMSE 0.4840), perbedaan ini tidak signifikan, menunjukkan bahwa model tidak terlalu overfit. Metrik MAE, MSE, dan RMSE pada kedua set data menunjukkan kesalahan prediksi yang relatif rendah, dengan nilai lebih tinggi pada set uji (MAE 0.3091 dan RMSE 0.5339), yang sedikit menunjukkan penurunan kinerja saat diuji pada data yang belum pernah dilihat. Secara keseluruhan, model ini cukup baik dan dapat diandalkan untuk prediksi dengan performa yang konsisten.

## Polynomial Regression
"""

from sklearn.preprocessing import PolynomialFeatures

poly_reg = PolynomialFeatures(degree=2)

X_train_2_d = poly_reg.fit_transform(X_train)
X_test_2_d = poly_reg.transform(X_test)

lin_reg = LinearRegression()
lin_reg.fit(X_train_2_d,y_train)

test_pred = lin_reg.predict(X_test_2_d)
train_pred = lin_reg.predict(X_train_2_d)

print('Test set evaluation:\n_____________________________________')
print_evaluate(y_test, test_pred)
print('====================================')
print('Train set evaluation:\n_____________________________________')
print_evaluate(y_train, train_pred)

results_df_2 = pd.DataFrame(data=[["Polynomial Regression", *evaluate(y_test, test_pred), 0]],
                            columns=['Model', 'MAE', 'MSE', 'RMSE', 'R2 Square', 'Cross Validation'])
results_df = pd.concat([results_df, results_df_2], ignore_index=True)

"""Model Polynomial Regression menunjukkan hasil yang sangat berbeda antara data train dan data test. Pada data test, model memiliki performa yang baik dengan R² sebesar 0.7905, yang berarti model dapat menjelaskan sekitar 79% variasi data, dengan MAE 0.3275, MSE 0.2547, dan RMSE 0.5047 yang menunjukkan kesalahan prediksi yang relatif rendah. Namun, pada data train, model menunjukkan hasil yang hampir sempurna dengan R² = 1, MAE, MSE, dan RMSE yang sangat kecil (dekat dengan nol), yang mengindikasikan bahwa model sangat cocok dengan data train, bahkan hingga overfitting. Ini berarti model polynomial telah menyesuaikan diri dengan sangat baik dengan data train, tetapi performanya pada data uji masih menunjukkan kesalahan yang lebih tinggi, yang mungkin disebabkan oleh kemampuan model yang terlalu tinggi untuk menangkap pola data train, mengarah pada kurangnya generalisasi ke data test.

## Stochastic Gradient Descent
"""

from sklearn.linear_model import SGDRegressor

sgd_reg = SGDRegressor(n_iter_no_change=250, penalty=None, eta0=0.0001, max_iter=100000)
sgd_reg.fit(X_train, y_train)

test_pred = sgd_reg.predict(X_test)
train_pred = sgd_reg.predict(X_train)

print('Test set evaluation:\n_____________________________________')
print_evaluate(y_test, test_pred)
print('====================================')
print('Train set evaluation:\n_____________________________________')
print_evaluate(y_train, train_pred)

results_df_2 = pd.DataFrame(data=[["Stochastic Gradient Descent", *evaluate(y_test, test_pred), 0]],
                            columns=['Model', 'MAE', 'MSE', 'RMSE', 'R2 Square', 'Cross Validation'])
results_df = pd.concat([results_df, results_df_2], ignore_index=True)

"""Model Stochastic Gradient Descent (SGD) menunjukkan hasil yang baik pada kedua set data, dengan sedikit perbedaan antara data train dan data test. Pada data test, model memiliki R² sebesar 0.8505, yang berarti dapat menjelaskan sekitar 85% variasi data, dengan MAE 0.2517, MSE 0.1818, dan RMSE 0.4264, yang menunjukkan kesalahan prediksi yang relatif rendah. Pada data train, R² sedikit lebih rendah, yaitu 0.8385, namun masih sangat baik, menunjukkan bahwa model dapat menjelaskan sekitar 83.85% variasi data. Meskipun kesalahan pada data train (MAE 0.2263, MSE 0.1527, RMSE 0.3908) sedikit lebih rendah, perbedaan ini tidak signifikan, yang mengindikasikan bahwa model tidak mengalami overfitting dan memiliki kemampuan generalisasi yang baik. Secara keseluruhan, model SGD memberikan hasil yang akurat dan cukup stabil pada kedua set data.

## Neural Network
"""

!pip install tensorflow

import tensorflow as tf
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense, Activation, Dropout
from tensorflow.keras.optimizers import Adam

# Convert the data to a consistent data type (float32)
X_train = np.array(X_train, dtype=np.float32)
X_test = np.array(X_test, dtype=np.float32)
y_train = np.array(y_train, dtype=np.float32)
y_test = np.array(y_test, dtype=np.float32)

model = Sequential()

model.add(Dense(X_train.shape[1], activation='relu'))
model.add(Dense(32, activation='relu'))
# model.add(Dropout(0.2))

model.add(Dense(64, activation='relu'))
# model.add(Dropout(0.2))

model.add(Dense(128, activation='relu'))
# model.add(Dropout(0.2))

model.add(Dense(512, activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(1))

model.compile(optimizer=Adam(0.00001), loss='mse')

r = model.fit(X_train, y_train,
              validation_data=(X_test,y_test),
              batch_size=1,
              epochs=100)

pd.DataFrame({'True Values': y_test, 'Predicted Values': pred}).hvplot.scatter(x='True Values', y='Predicted Values')

"""* Model menunjukkan kemampuan prediksi yang cukup baik pada data di sekitar nilai 0, di mana sebagian besar titik mendekati garis diagonal.
* Namun, terdapat deviasi pada beberapa titik, terutama pada nilai sebenarnya yang lebih ekstrem (baik negatif maupun positif). Hal ini menunjukkan bahwa model mungkin masih kesulitan memprediksi nilai yang di luar distribusi mayoritas data.
"""

pd.DataFrame(r.history)

pd.DataFrame(r.history).hvplot.line(y=['loss', 'val_loss'])

"""Grafik ini menunjukkan nilai loss (error) selama untuk data training dan validasi. Sumbu Y merepresentasikan nilai Mean Squared Error (MSE), dan sumbu X menunjukkan jumlah epoch.

Dari grafik ini terlihat:

* Terlihat awalnya loss dan validation loss menurun dengan cepat, yang
menunjukkan bahwa model mempelajari pola data.
* Setelah sekitar 20 epoch, validation loss cenderung stagnan sementara training loss terus menurun. Hal ini menunjukkan model mulai overfitting terhadap data training.
* Pada epoch ke-100, training loss lebih rendah daripada validation loss, yang menjadi indikasi model belajar lebih baik pada data training dibandingkan data validasi.

Pengaruh Ukuran Data dan Pemilihan Epoch

Ukuran data yang besar memengaruhi kebutuhan training model. Dalam kasus ini, jumlah epoch yang dipilih (100 epoch) mungkin belum cukup untuk memaksimalkan kemampuan model. Dengan data besar, model sering memerlukan lebih banyak epoch untuk menangkap pola yang kompleks, tetapi harus dilakukan dengan hati-hati untuk menghindari overfitting.
"""

test_pred = model.predict(X_test)
train_pred = model.predict(X_train)

print('Test set evaluation:\n_____________________________________')
print_evaluate(y_test, test_pred)

print('Train set evaluation:\n_____________________________________')
print_evaluate(y_train, train_pred)

results_df_2 = pd.DataFrame(data=[["Neural Network", *evaluate(y_test, test_pred), 0]],
                            columns=['Model', 'MAE', 'MSE', 'RMSE', 'R2 Square', 'Cross Validation'])
results_df = pd.concat([results_df, results_df_2], ignore_index=True)

"""1. Evaluasi Data Test (Data Validation)

* Mean Absolute Error (MAE): 0.23386112
* Mean Squared Error (MSE): 0.1684379
* Root Mean Squared Error (RMSE): 0.41041186
* R-squared (𝑅²): 0.8615049123764038

Nilai 𝑅² sebesar 0.8615 menunjukkan bahwa model mampu menjelaskan sekitar 86.15% variabilitas dalam data uji. Namun, adanya error yang tercermin pada MAE, MSE, dan RMSE menunjukkan bahwa model masih mengalami kesulitan dalam menangkap pola tertentu, terutama untuk nilai ekstrem atau di luar distribusi mayoritas.

2. Evaluasi Data Training

* Mean Absolute Error (MAE): 0.03027812
* Mean Squared Error (MSE): 0.0018284029
* Root Mean Squared Error (RMSE): 0.04275983
* R-squared (𝑅²): 0.9980666637420654

Pada data training, model menunjukkan performa yang sangat baik, dengan nilai 𝑅² sebesar 0.998, MAE yang sangat rendah (0.030), dan MSE/RMSE yang hampir mendekati nol. Hal ini menunjukkan bahwa model dapat mempelajari data training dengan sangat baik.

## Random Forest
"""

from sklearn.ensemble import RandomForestRegressor

rf_reg = RandomForestRegressor(n_estimators=1000)
rf_reg.fit(X_train, y_train)

test_pred = rf_reg.predict(X_test)
train_pred = rf_reg.predict(X_train)

print('Test set evaluation:\n_____________________________________')
print_evaluate(y_test, test_pred)

print('Train set evaluation:\n_____________________________________')
print_evaluate(y_train, train_pred)

results_df_2 = pd.DataFrame(data=[["Random Forest Regressor", *evaluate(y_test, test_pred), 0]],
                            columns=['Model', 'MAE', 'MSE', 'RMSE', 'R2 Square', 'Cross Validation'])

results_df = pd.concat([results_df, results_df_2], ignore_index=True)

"""1. Evaluasi Data Uji (Test Set)
* Mean Absolute Error (MAE): 0.218634564
* Mean Squared Error (MSE): 0.128886067
* Root Mean Squared Error (RMSE): 0.359007057
* R-squared (𝑅²): 0.894025735

Nilai 𝑅² sebesar 0.8940 menunjukkan bahwa model mampu menjelaskan sekitar 89.40% variabilitas pada data uji, yang merupakan indikasi performa prediksi yang sangat baik. Nilai error yang relatif rendah pada MAE (0.2186), MSE (0.1289), dan RMSE (0.3590) menunjukkan bahwa model dapat menangkap pola dari data uji dengan akurasi yang cukup baik.

2. Evaluasi Data Training (Train Set)
* Mean Absolute Error (MAE): 0.080601662
* Mean Squared Error (MSE): 0.019118301
* Root Mean Squared Error (RMSE): 0.138268943
* R-squared (𝑅²): 0.979784716

Pada data training, model menunjukkan performa yang sangat baik, dengan nilai 𝑅² sebesar 0.9798 (hampir mendekati 1). MAE, MSE, dan RMSE juga menunjukkan error yang sangat rendah, yang berarti model mampu mempelajari data training dengan baik.

## Support Vector Regressor
"""

from sklearn.svm import SVR

svm_reg = SVR(kernel='rbf', C=1000000, epsilon=0.001)
svm_reg.fit(X_train, y_train)

test_pred = svm_reg.predict(X_test)
train_pred = svm_reg.predict(X_train)

print('Test set evaluation:\n_____________________________________')
print_evaluate(y_test, test_pred)

print('Train set evaluation:\n_____________________________________')
print_evaluate(y_train, train_pred)

results_df_2 = pd.DataFrame(data=[["SVM Regressor", *evaluate(y_test, test_pred), 0]],
                            columns=['Model', 'MAE', 'MSE', 'RMSE', 'R2 Square', 'Cross Validation'])
results_df = pd.concat([results_df, results_df_2], ignore_index=True)

"""1. Evaluasi Data Uji (Test Set)
* Mean Absolute Error (MAE): 87,205.73
* Mean Squared Error (MSE): 11,720,932,765.28
* Root Mean Squared Error (RMSE): 108,263.26
* R-squared (𝑅²): 0.9007

Nilai 𝑅² sebesar 0.9007 menunjukkan bahwa model mampu menjelaskan sekitar 90.07% variabilitas pada data uji, yang merupakan indikasi performa prediksi yang sangat baik. Nilai error yang cukup tinggi pada MAE (87,205.73), MSE (11,720,932,765.28), dan RMSE (108,263.26) menunjukkan adanya beberapa error besar, tetapi model masih mampu menangkap pola pada data uji dengan akurasi yang cukup baik.

* Evaluasi Data Training (Train Set)
* Mean Absolute Error (MAE): 73,692.57
* Mean Squared Error (MSE): 9,363,827,731.41
* Root Mean Squared Error (RMSE): 96,766.87
* R-squared (𝑅²): 0.9265

Pada data training, model menunjukkan performa yang sangat baik, dengan nilai 𝑅² sebesar 0.9265 (hampir mendekati 1). MAE, MSE, dan RMSE juga menunjukkan error yang lebih rendah dibandingkan data uji, yang berarti model mampu mempelajari data training dengan sangat baik.

# Model Comparison
"""

results_df

results_df['R2 Square']

results_df.set_index('Model', inplace=True)
results_df['R2 Square'].plot(kind='barh', figsize=(12, 8))

"""Berdasarkan hasil setiap model, model terbaik untuk menjelaskan variasi dari variabel respon adalah model Random Forest dan berikut adalah alasannya.

* R² tertinggi: Model ini memiliki nilai R² sebesar 0.8929, yang berarti mampu menjelaskan 89,29% variabilitas data, paling tinggi dibanding model lain.
* Error terendah: MAE (17,456) dan RMSE (28,665) jauh lebih rendah dibanding model lainnya, menunjukkan prediksi yang paling akurat.
* Konsistensi performa: Performa pada evaluasi menunjukkan bahwa model ini sangat baik dalam menangkap pola data.

# Submission
"""
# Prediksi pada data test
test_pred = rf_reg.predict(test_scale)

subm = pd.read_csv('/content/regresi/sample_submission.csv')
subm['SalePrice'] = test_pred
subm.head()

# Simpan hasil prediksi ke csv
subm.to_csv('submission.csv', index=False)
